from enum import StrEnum


class ErrorTypeEnum(StrEnum):
    HTTP_EXCEPTION = "HTTP_EXCEPTION"
    UNAUTHORIZED = "UNAUTHORIZED"  # 未认证
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"  # 无效的凭证（用户名或密码）
    TOKEN_INVALID = "TOKEN_INVALID"  # 无效的令牌
    TOKEN_EXPIRED = "TOKEN_EXPIRED"  # 过期的令牌
    PERMISSION_DENIED = "PERMISSION_DENIED"  # 权限拒绝
    USER_DISABLED = "USER_DISABLED"  # 用户被禁用
    USER_NOT_VERIFIED = "USER_NOT_VERIFIED"  # 用户未认证
    ITEM_NOT_FOUND = "ITEM_NOT_FOUND"  # 资源未找到
    USERNAME_TAKEN = "USERNAME_TAKEN"  # 用户名被占用
    EMAIL_TAKEN = "EMAIL_TAKEN"  # 邮箱被占用
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"  # 请求体过大
    DATA_VALIDATION = "DATA_VALIDATION"  # 数据验证失败
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"  # 请求过于频繁
    INTERNA_SERVER_ERROR = "INTERNA_SERVER_ERROR"  # 内部服务器错误
